---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.23.11, namelong: vg-docker-01.local, nameshort: vg-docker-01 }
  - { ip: 192.168.23.12, namelong: vg-docker-02.local, nameshort: vg-docker-02 }
  - { ip: 192.168.23.13, namelong: vg-docker-03.local, nameshort: vg-docker-03 }
  - { ip: 192.168.23.14, namelong: vg-docker-04.local, nameshort: vg-docker-04 }    
  when: add_host_entries
