---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
  tasks:
    - name: "Disable SELinux"
      selinux:
        state: disabled

    - name: "upgrade all packages"
      yum:
        name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
        #state: latest
        update_cache: yes

    - name: "Install zabbix packages"
      package:
        state: installed
        name:
          - vim

# - name: "Install docker-ce and docker-compose-ce"
#   gather_facts: true
#   hosts:  vg-docker-01
#   become: yes
#   roles:
#     - docker-compose
# - name: "Install docker-ce and docker-compose-ce"
#   gather_facts: true
#   hosts:  vg-docker-03
#   become: yes
#   roles:
#     - docker-compose
